---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Introducción

Despues de haber estudiado el coas y su comportamiento tanto en modelos matemáticos como la función logística y en sistemas físicos como el péndulo doble y la predicción meteorológica y climática, me he propuesto crear mi propio sitema caótico para poder estudiarlo y hallar sus similitudes y relaciones con el resto de sitemas caósticos estudiados. Para hacer mi sistema caótico primero probé a construirlo con mis propias manos pero después de varios prototipos del sistema que no conseguí que funcionaran o que tuvieran un coportamiento caótico decidí hacerlo en un simulador de física llamado Algoodo. 
El modelo y el diseño para que tuviera un movimiento caótico lo mantuve igual que en los prototipos anteriores solo que esta vez al ser un simulador podía ajustar todos los parametros con mucha más precisión que haciendolo a mano, donde no tengo tanta precisión de todas las medidas. 
Esta vez, haciéndolo en un simulador si que funcionó todo a la perfección. Una ventaja que tuve al hacer mi sistema en un simulador fue que el simulador me daba la opcion de tener gráficos de las medidas como la velocidad, la velocidad angular o el centro de masas en tiempo real y de luego descargarlos y obtener todos los datos facilmente.