---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Cambios Climáticos Rápidos

Tal y como comentamos en la sección anterior, el clima global de la Tierra se puede ver sujeto a cambios abruptos en cortos espacios de tiempo. Esta es una manifestación más de la naturaleza caótica del clima, que hasta los años 50 del pasado siglo, se consideraba que no podría ocurrir. Sin embargo los científicos han encontrado estas variaciones abruptas del clima de la Tierra en los últimos 15.000 años, desde el final de la última glaciación.  Ha habido dos eventos muy relevantes que muestran como el clima puede cambiar bruscamente.


## Evento "Younger Dryas" (≈ 12 900–11 700 años antes del presente)
 Imagina que, al final de la última glaciación, la temperatura sube lentamente y, de pronto, en menos de dos siglos, ¡cae 5 °C! Sería como pasar de un día de primavera suave a un día de invierno extremo en unas pocas generaciones humanas[^1]. Esto fue lo que pasó hace 12900 años debido a que un gran volumen de agua dulce de deshielo de un lago fue vertido en el atlántico norte y bloqueó la Corriente del Golfo, reduciendo el transporte de calor al Atlántico Norte. La reducción de temperatura tuvo lugar a lo largo de unas pocas décadas y su impacto duró 1200 años. La salida de este estado climático también fue muy rápida. Se estima que también en unas pocas décadas volvió a aumentar la temperatura media unos 5 grados.

## Evento 8.2 k (≈ 8 200 años antes del presente)
Tras el Younger Dryas, unos 4 700 años después, se produjo otra bajada de ~3 °C que duró 150 años. Es equivalente a cambiar de clima templado a casi boreal en unas pocas generaciones[^1]. De nuevo, el causante fue el desagüe repentino del lago glacial Agassiz–Ojibway en Norteamérica, vertiendo enormes volúmenes de agua dulce en el Atlántico. Se estima que el descenso de temperatura tuvo lugar en menos de 10 años, y que la recuperación fue más gradual, unos 50 años.

## Conexión común. Puntos de inflexión del clima

Estos eventos destacan la no linealidad del sistema climático y su **sensibilidad extrema a perturbaciones**. Una pequeña alteración en la salinidad u origen de agua dulce puede desencadenar un cambio rápido y global del clima. En la actualidad los científicos del clima han identificado varios puntos de inflexión que podrían provocar un cambio brusco del clima, como:

- Parón repentino de la corriente del Golfo debido al descenso de salinidad debido al agua dulce procedente del deshielo del Ártico y de los ríos siberianos.
- Liberación de enormes cantidades de metano si se derrite el permafrost, lo que originaría una aceleración del calentamiento de la Tierra

Como dijimos anteriormente, son muchos los factores que intervienen en el clima. El poder tener en cuenta todos, implica un modelado de mucha precisión de una multitud de factores. En el futuro se podría desencadenar un evento que provocase un punto de inflexión y que diera al traste con las predicciones realizadas con los modelos actuales. Por ejemplo, en la pequeña edad del hielo, (aproximadamente entre 1300 y 1850), se cree que los factores que desencadenaron el descenso global de las temperaturas fueron una mayor actividad volcánica que coincidió con un mínimo de actividad solar. Estas dos perturbaciones causaron alteraciones en las corrientes oceánicas que habrían amplificado el enfriamiento, especialmente en el hemisferio norte. Tener en cuenta este tipo de eventos en un simulador, resulta imposible. 

Un ejemplo extremo de punto de inflexión son los ciclos de Milankovitch. Estos ciclos periódicos que marcan los cambios de la excentricidad de la órbita de la Tierra, y la inclinación del eje de la Tierra, han marcado durante los últimos 5 millones de años la llegada y marcha de las glaciaciones. Pero lo interesante, es que estos pequeños cambios en la órbita de la Tierra, por sí solos no son capaces de generar las glaciaciones. Son puntos de inflexión, que provocan una cascada de eventos posterior que amplifican la pequeña perturbación inicial. 

Por lo tanto, vemos como no solamente es necesario tener un buen simulador de la circulación atmosférica/oceánica, sino que también habría que tener en cuenta aspectos geológicos de la Tierra, sus ecosistemas, e incluso posibles perturbaciones cósmicas. 

En la siguiente sección evaluaremos como han funcionado los modelos que se usan para la predicción del clima. Si bien, desde el momento en el que se empezaron a usar estos modelos no ha habido cambios naturales grandes, veremos como se han comportado durante este último siglo en el que el principal forzamiento del clima ha sido la emisión de gases de efecto invernadero por parte del ser humano. 

---

[^1]: AIP History of Physics, "Rapid Climate Change", consultado el 5 de julio de 2025.  
[^2]: Wikipedia en español, "Dansgaard–Oeschger event", consultado el 5 de julio de 2025.  
