---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Simulación y funcionamiento caótico

Una vez construida la rueda en el simulador y despues de haber comprobado que todo funcionaba correctamente empece con las simulaciones del sistema.

Primero corrí la simulación cinco veces durante 180 segundos cada vez y en todas ellas establecí exactamente las mismas condiciones iniciales para todos los parámetros. Estos parámetros son te´´oricamente idénticos todas las veces que he ejcutado la simulación ya que el programa me permite hacer varias copias de un estado del sistema para despues poder correr la simulación varias veces con las mismas exactas condiciones iniciales.

En cada una de las simulaciones use una opción de Algodoo para tener grabados los datos de velocidad angular instantanea de la rueda, de la posición x (en el eje horizontal) del centro de masas de las canicas a lo largo del tiempo y de la posició en y (en el eje vertical) del centro de masas de las canicas.