---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Resumen del Proyecto de Investigación

Desde tiempos inmemoriales el ser humano ha ansiado conocer el futuro. En la antigüedad, las culturas anteriores al desarrollo de la ciencia recurrían a la magia, oráculos y al esoterismo para tratar de predecir el futuro. Con la llegada del método científico, la Humanidad pudó conocer las leyes que rigen el Universo para así poder predecir el comportamiento de muchos fenómenos naturales. La mecánica de Newton permitió calcular trayectorias de planetas y cometas con gran precisión; la termodinámica y la química explicaron reacciones y transformaciones de la materia; la biología comenzó a anticipar procesos vitales como la herencia genética.

Durante siglos, esta idea de que si conocemos las leyes y las condiciones iniciales podemos anticipar el futuro fue dominante en la ciencia. Sin embargo, a mediados del siglo XX surgió un descubrimiento sorprendente: incluso en sistemas gobernados por leyes deterministas, pequeñas variaciones en los datos iniciales podían producir resultados totalmente distintos.

Este fenómeno recibió el nombre de caos, y cambió para siempre nuestra concepción de la predicción. Podíamos conocer las leyes que rigen el Universo, pero la capacidad de conocer el futuro era limitada. 

Para poder comprender el alcance del del caos sobre la capacidad de predicción recurrí en primer lugar a analizar el fenómeno en el ordenador. Y es que es el ordenador el medio por el cual realizamos cálculos complejos basados en modelos matemáticos de la realidad que nos rodea. Como campo de experimentación escogí el mapa logístico, por ser una sucesión sencilla que presenta un comportamiento caótico muy complejo. Realicé un experimento muy impactante, que fue codificar el mapa logístico de dos maneras diferentes, como $x_{n+1} = r\,x_n\,(1 - x_n)$ y como $x_{n+1} = r\,x_n - r\,{x_n}^2$. Al cabo de pocas iteraciones pude ver como los resultados de ambas fórmulas divergían enormemente debido a la precisión finita de almacenaje de los números en el ordenador. 

Ante estos resultados tan desconcertantes, me pregunté si el caos también se da de forma tan fácil en sistemas físicos. Para ello recurrí al análisis del péndulo doble, que es uno de los sistemas caóticos por antonomasia. Para ello, pedí a ChatGPT que me desarrollase las ecuaciones matemáticas que rigen el movimiento del péndulo y que me las simulase bajo multitud de estados iniciales diferente, ligeramente separados unos de otros. Los desarrollos fueron codificados por ChatGPT en Python y simulados en mi ordenador. Algunas de las simulaciones implicaban el lanzamiento en paralelo de miles de péndulos y eran muy lentas ejecutadas en la CPU del ordenador, por lo que tuve que recurrir a que ChatGPT paralelizase los programas usando las librerías de Python para la tarjeta gráfica Nvidia de mi ordenador. Los resultados fueron de nuevo sorprendentes, pues empezaron a aparecer estructuras fractales dentro de las condiciones iniciales cuando simulaba miles de péndulos a la par. No importaba como de pequeña era la diferencia de condiciones iniciales entre dos péndulos, que al final, con el transcurso del tiempo, los péndulos dobles siempre divergían.

Una vez terminada la parte de análisis matemático y de simulación de los sistemas caóticos, me lancé a comprobar si en verdad este comportamiento caótico se daba en la realidad. Para ello compré un péndulo doble, que tenía la propiedad de poder bloquear el segundo eje para así transformarse en un péndulo simple. Aquí el reto estaba en poder medir con precisión la posición de los dos brazos del péndulo mientras se movía a alta velocidad. Tras ser aconsejado por ChatGPT, recurrí a una librería de visión por ordenador llamada OpenCV. Con la ayuda de ChatGPT realicé un programa que, en tiempo real, medía la posición de los brazos del péndulo doble y guardaba los datos en un fichero. Gracias a este programa, pude ver que lanzando el péndulo doble en diferentes ocasiones desde la misma posición inicial, las trayectorias divergían enormemente tras unos breves instantes. Me pregunté si habría algún problema con la forma en la que estaba configurado el experimento, así que recurrí a hacer lo mismo con el péndulo simple. En este caso, pude ver, como una tras otra, las trayectorias eran idénticas en todos los lanzamientos.

Llegado a este punto y convencido del comportamiento caótico de sistemas aparantemente sencillos, quise ver como se manifestaba el caos en sistemas más complejos, como es la atmósfera terrestre y la meteorología, y también quise ver como lidiaba la ciencia con este asunto. Si bien pude ver como existían modelos de código abierto con los que simular la atmósfera, no disponía la capacidad de cómputo para ello. Por ello, y tras investigar el tema, llegué a la conclusión de que el mayor error que se da en las predicciones es el debido a la imprecisión en las condiciones iniciales, no a las ecuaciones que rigen los modelos. Entonces, pensé que observando como diverge la observación de la predicción realizada unos días antes, podría cuantificar el crecimiento exponencial del caos debido a la sensibilidad a las condiciones iniciales, manifestada a través del error con el que se observan las variables meteorológicas. Creé con ChatGPT un programa, que día tras día, se conectaba a una web meteorológica y que me daba las predicciones para los siguientes 14 días. Almacené esos datos durante tres meses, y después los analicé. Pude así ver con datos reales el crecimiento exponencial de los errores, y hacer un análisis de regresión para calcular el exponente de Lyapunov de las variables meteorológicas principales: temperatura, presión, humedad y velocidad del viento. Corroboré este procedimiento y pude despejar algunas dudas con técnicos de predicción de la AEMET, quienes tuvieron la amabilidad de charlar conmigo sobre el impacto del caos en meteorología durante una mañana. A la vista de mis resultados y de los datos que me aportaron los técnicos de la Aemet, pude determinar como el horizonte de predicitibilidad de las variables meteorológicas no va nunca más alla de los 14 días. Y es una barrera muy difícil de superar, pues mientras que nuestras mejoras en la toma de datos avanzan linealmente, el error caótico evoluciona exponencialmente con el tiempo. 

Siguiendo con esta dinámica, quise ampliar el análisis de la prediccion de la atmósfera, estudiando esta vez el comportamiento de los modelos a largo plazo, es decir, estudiar la precisión con la que los modelos climáticos habían sido capaces de predecir hasta ahora el clima. Realicé una investigación de las principales predicciones realizadas hace 20, 30 años y ví su grado de cumplimiento en la actualidad. Si bien la principal variable, la temperatura media de la Tierra, había sido predicha con precisión, a nivel regional había algunas discrepancias entre las observaciones y las predicciones. La ralentización del deshielo del ártico, el no crecimiento del número de huracanas, la menor subida del nivel del mar, la no disminución de las precipitaciones en los países mediterráneos, son algunos ejemplos de predicciones fallidas que encontré. Y es que el IPCC ha reconocido que en muchos casos, el comportamiento caótico del clima puede limitar nuestra capacidad de hacer predicciones certeras a largo plazo especialemente a escala regional. Y este último punto resulta muy importante, puesto que un enfoque prudente refuerza la necesidad de proteger los ecosistemas y reducir las emisiones de gases de efecto invernadero, dado que el resultado detallado de nuestras acciones es incierto. No deberíamos especular con el impacto de nuestras acciones en un sistema que somos incapaces de predecir correctamente. La incertidumbre no nos exime de responsabilidad, sino que la refuerza.

Tras analizar sistemas caóticos en el ordenador, la naturaleza y en los modelos climáticos, quise dar un paso más y preguntarme si sería capaz de crear yo mismo un sistema caótico artificial. No se trataba ya de estudiar únicamente ejemplos existentes, sino de experimentar con la posibilidad de generar caos en un entorno controlado. Para ello utilicé el simulador físico Algodoo, donde diseñé una rueda movida por la caída de agua y convertida en caótica por la acción de canicas sueltas en su interior. Pude ver como el atractor surgido de este sistema era muy similar al de Lorenz, con dos estados (velocidad angular positivia y negativa), de los que se sale de forma totalmente impredecible.

Por último y cansado de ver el caos como algo negativo que dificulta nuestra capacidad de predecir el futuro, me metí en el campo filosófico y especialmente en el trabajo de Prigogine sobre el caos, como fenómeno creador de nuevas estructuras, indispensable para la aparición de estructuras complejas como la vida en la Tierra. Tras empaparme de la teoría de Prigogine, y en base a lo observado en mi investigación, formulo la siguiente Tesis:

* En sistemas estables/no caóticos, el comportamiento es altamente predecible y la información inicial se conserva con poca distorsión; por eso la novedad estructural es limitada.

* En sistemas inestables/caóticos, el aporte de energía y la sensibilidad a perturbaciones dispersan (“diluyen”) la información inicial, abriendo bifurcaciones y creando nuevas estructuras. A cambio, disminuye la predictibilidad detallada más allá de un horizonte de predicción.

El principio heurístico que se deduce es el siguiente:

"No es posible maximizar simultáneamente la predictibilidad detallada y la creación de novedad en sistemas dinámicos complejos: cuanto más creativa (abierta a nuevas estructuras) es la evolución, menos plenamente predecible es su trayectoria fina, y viceversa"

Por lo tanto, la tan ansiada omnisciencia en un universo creativo como el nuestro es un oxímoron. Podemos determinar patrones, pero no ver los detalles finos, es decir, podemos anticipar patrones (atractores, rangos de comportamiento, escenarios probables) mejor que trayectorias exactas a largo plazo. Cuanto mayor sea el aporte energético, mayor sera el caos, y menor será la predictibilidad, pero al mismo tiempo se aumentarán las posibilidades de creación de nuevas estructuras. 

Un universo capaz de crear nuevas formas no puede ser, al mismo tiempo, totalmente transparente a nuestra predicción. La novedad tiene un precio: nos hace renunciar a una parte de la certeza. Es como si los sistemas que conforman el Universo no se dejasen modelar o simular. 

Por tanto, la creación de nuevas estructuras no puede predecirse matemáticamente (ni con simulaciones por ordenador): surge del propio universo. Es como si la evolución cósmica escapase a nuestra capacidad de predicción. Uno puede hacerse el experimento mental: ¿habría sido posible, en el instante del Big Bang, imaginar o simular que, a partir de un punto de energía infinita, surgiría un planeta como la Tierra, con vida y una civilización avanzada como la nuestra? Del mismo modo, ¿podríamos modelar o simular de antemano la aparición de vida compleja a partir de moléculas sencillas de carbono, hidrógeno, nitrógeno y oxígeno?

En definitiva, podemos plantear que "la novedad estructural es impredecible en detalle en un sistema caótico". Y quizá ahí resida el misterio más fascinante del universo: que la misma dinámica que limita nuestra capacidad de predecir el futuro es la que permite la emergencia de la vida, de la complejidad y de la creatividad. El caos no es un obstáculo al conocimiento, sino el terreno fértil donde nace lo nuevo.