---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Estudio formal del mapa logístico
En los siguientes apartados vamos a desentrañar desde un punto de vista matemático como se comporta el mapa logístico. Ya hemos visto en los apartados anteriores, vía simulación, que el comportamiento es muy errático dependiendo del valor de $r$. Veamos por qué.

Para empezar veremos la función logística y la analizaremos como haríamos con cualquier otra función para ver su forma. Para ello, recurrimos a las técnicas habituales de analisis de funciones.

## Dominio y ceros
- Por definición, el **Dominio** es: $0 \le x \le 1$  
- En este dominio los **Ceros** de la función están en:  
  - $f(0) = r \cdot 0 \cdot (1-0) = 0$  
  - $f(1) = r \cdot 1 \cdot (1-1) = 0$

## Derivada y monotonía
Para conocer los máximos y mínimos primero hemos de calcular la derivada,

- Derivada:  
  $$f'(x) = r(1 - 2x)$$  
- La derivada tiene una raíz en $x=1/2$, independientemente del valor de $r$. Por lo tanto, el signo de $f'(x)$:  
  - Si $0 \le x < \tfrac12$, entonces $f'(x) > 0$ ⇒ **creciente**  
  - Si $x = \tfrac12$, entonces $f'(x) = 0$  
  - Si $\tfrac12 < x \le 1$, entonces $f'(x) < 0$ ⇒ **decreciente**

De acuerdo al estudio de la derivada, tenemos un punto crítico en $x = \tfrac12$. Puesto que la derivada pasa a ser creciente a decreciente en este punto, tenemos un máximo. La función, pues, tiene un valor máximo:  
  $$f\bigl(\tfrac12\bigr) = \frac{r}{4}$$

Observar que si $r>4$ entonces el máximo de la función es mayor que 1. Esto no puede darse, ya que la funcíón logística normaliza los recursos máximos disponibles a 1. Por lo tanto, para que no se excedan (cosa que no puede ocurrir físicamente), el valor de r siempre se establece por debajo de 4. 

## Concavidad
- Segunda derivada:  
  $$f''(x) = -2r$$  
- Como $r>0$, $f''(x)<0$ en todo el dominio ⇒ **cóncava hacia abajo**

## Rango de la función
De acuerdo, al estudio anterior, la función es siempre positiva, con valores entre $0$ y $\tfrac{r}{4}$  

Si vamos a la sección con el diagrama de telaraña, veremos efectivamente esta forma de la función. 

## Resumen gráfico
- Parábola invertida con vértice en $\bigl(\tfrac12,\tfrac{r}{4}\bigr)$  
- Crece de $x=0$ a $x=\tfrac12$, luego decrece hasta $x=1$
