---
format:
  html:
    math: katex
execute:
  enabled: true
  echo: false
---

# Determinismo e Inteligencia Artificial

La existencia del Caos tiene claras implicaciones filosóficas. Una de las grandes aspiraciones del ser humano es saber si seremos capaces de conocer el futuro del Universo o de cualquier sistema o del entorno que nos rodea; un nivel de conocimiento cercano a la Omniscencia. El avance de la ciencia, el incremento de capacidades de los sistemas computacionales y la llegada de la inteligencia artificial nos puede hacer pensar que el momento en que el podamos tener un conocimiento total del universo se acerca. Sin embargo el Caos nos impone un límite al nivel de conocimiento que podemos tener del futuro. De la misma manera que existen límities físcos claros, como el de la velocidad de la luz, y por mucho que nos empeños nunca vamos a poder viajar más rápido que la luz, en la parte del conocimiento del futuro, el caos limita el horizonte de predictibilidad. Siguiendo con las analogías traídas de la Física, el Horizonte de Predictibilidad es como el Horizonte de Sucesos en los agujeros negros. Para cualquier observador externo, es imposible obtener información local sobre lo que ocurre mas allá del horizonte de sucesos de un agujero negro: no hay señal, información o luz que pueda salir de ahí y llegar hasta nosotros. No podemos acceder a información local del interior; sólo podemos inferir propiedades globales desde fuera y hacer predicciones teóricas sobre cómo debería ser el interior según nuestras mejores teorías. Algo así ocurre con el horizonte de predicitibilidad. Más allá de él, no podremos saber qué es lo que ocurre con un gran nivel de detalle, pero sí podremos estimar comportamientos en términos estadísticos: rangos probables, tendencias y escenarios. 

El caos, por tanto, no niega que existan leyes; nos recuerda que nuestro conocimiento práctico tiene límites y debe expresarse con incertidumbres bien cuantificadas. En resumidas cuentas, un sistema puede ser determinista pero no predecible. El caos no niega leyes físicas, pero nos obliga a cuantificar las incertidumbres de nuestras predicciones. 

## Determinismo 

A continuación veremos como enlaza el Caos con la corriente filosófica del determinismo. El determinismo, en breve, asegura que bajo las “mismas causas, tendremos los mismos efectos”. La idea del determinismo tuvo su expansión durante los siglos XVII y XVIII debido al desarrollo de la mecánica Newtoniana y al gran desarrollo posterior de la física y las matemáticas. Tuvo su mayor exponente ya en el siglo XIX con la propuesta del "demonio de Laplace": una inteligencia superior que tuviera un conocimiento absoluto del Universo en un momento dado. Gracias a las leyes matemáticas que rigen el Universo, a partir de un momento dado en el que se conociese el estado de todo el Universo, se podría conocer cualquier estado pasado o futuro del mismo. Un demonio de Laplace con capacidad infinita de computación y con precisión infinita para conocer el estado inicial del sistema, podría saber el estado futuro de nuestro clima, pues éste está regido por ecuaciones deterministas. Sin embargo, en la práctica nunca van a existir las dos condiciones que cumple el demonio de Laplace (infinita precisión e infinita capacidad de cómputo), por lo que el ser humano tendrá que lidiar con las limitaciones impuestas por el caos en sistemas deterministas como el clima. 

Obsérvese que, de acuerdo a la ciencia moderna, si bien el demonio de Laplace podría predecir el clima, no está demostrado que lo podría hacer con el Universo en general. Y es que a nivel cuántico hay principios físicos como el principio de incertidumbre de Heissemberg, que niegan la posibilidad de tener un conocimiento total del estado en el que se encuentran las partículas subatómicas. Es un límite en nuestro universo, que el demonio de Laplace no se puede saltar, y que por lo tanto limita su capacidad de predecir el futuro. 

Obsérvese también, que el determinismo no implica fatalismo. El fatalismo implica que daría igual lo que uno haga, que el determinismo afirma que el futuro ya está dictado. Esta afirmación no es correcta, ya que en determinismo las acciones de las personas también son causas y tienen el potencial de afectar al futuro, de una forma que el demonio de Laplace ya habrá predicho previamente. Es decir, nuestras decisiones estarían descontadas ya por el demonio de laplace, pero no por ello no dejan de estar sometidas a la libertad y libre albedrío de los seres humanos. Este punto es muy importante de comprender, porque si nos resignamos a que el futuro ya está escrito, nunca podríamos cambiarlo o al menos intentar cambiarlo, para mal o para bien. Y este cambio de destino es lo que buscamos en las siguientes secciones. 


## Inteligencia Artificial, Demonio de Laplace y Clima

Bajo las condiciones de determinismo el Clima puede ser predicho por un demonio de Laplace. Si tratamos al clima como un sistema aislado, como sistema determinista tendrá un único estado futuro posible, si bien este futuro no puede ser conocible para entes externos como nosotros debido a la existencia  del caos. La pregunta es, ¿podrá en el futuro una Superinteligencia Artificial hacer el trabajo de un Demonio de Laplace y ayudarnos a predecir el clima?. La respuesta corta es no, debido a que una Superinteligencia Artificial nunca podrá contar con un conocimiento infinitamente preciso de las condiciones iniciales ni con una capacidad de cómputo infinita, por lo que el caos acabará haciendo acto de presencia en las predicciones. 

Entonces, ¿en qué nos podrá ayuda una Superinteligencia Artificial en el futuro?. En primer lugar a generar mejores modelos y avanzar en la reducción de las incertidumbres. En segundo, lugar a controlar, no sólo a predecir el clima. En un sistema caótico, el ideal laplaciano de un oráculo omnisciente debe ceder al ideal de un controlador del sistema que sea capaz de configurar condiciones para que muchos futuros posibles converjan hacia escenarios deseables del conjunto total de escenarios posibles. Por lo tanto, podríamos usar nuestra Superinteligencia Artificial para diseñar estructuras que estrechen el abanico de futuros escenarios. El éxito de la Superinteligencia no estará tanto en acertar el clima futuro, sino en reducir la posibilidad de escenarios adversos y catástrofes, y en hacer el propio clima más robusto a sorpresas (tipping points). Por lo tanto, redefiniremos el papel de la superinteligencia en una super-ingeniería de reducción de incertimbure mediante el propio control del clima para convertir el caos en gobernabilidad sin pretender abolirlo.

¿Cómo es de factible este control del clima con una Superinteligencia Artificial?. Para responder a esta pregunta, hay que tener en cuenta que en la actualidad, el clima es un sistema complejo que involucra también a la Humanidad, y que a partir de ahora llamaremos sistema socio-climático. En la actualidad el clima de la Tierra está condicionado por la actuación de los seres humanos. Por lo tanto, la Superinteligencia Artificial tendrá que actuar no solo sobre el clima, sino también sobre el conjunto de los seres humanos para modificar su comportamiento. Y la Humanidad en su conjunto es un sistema anti-inductivo, que está unido al clima.

## Anti-inductivismo

Un sistema anti-inductivo es aquel en el que las regularidades inferidas por inducción dejan de ser válidas precisamente porque han sido descubiertas y explotadas. Es decir, la predicción cambia el propio sistema: los agentes se adaptan (o adversarios reaccionan) y rompen el patrón que acabábamos de aprender. Un ejemplo de ello es la bolsa de valores, en la que el aprendizaje de patrones de predicción de la evolución del precio de una acción y su posterior adopción en masa por el conjunto de compradores/vendedores de acciones, modifica el efector del propio predictor. 

Las Inteligencias Artificiales que está desarollando la Humanidad se basan en la detección de patrones. Y es que la inteligencia, bien sea natural o artificial, se base en la capacidad de descubrir estructuras regulares (patrones) en datos diversos y utilizarlas para predecir, planificar y actuar con éxito en situaciones nuevas. 

Como decíamos anteriormente, la Superinteligencia Artificial tendrá que actuar sobre el conjunto de seres humanos, en base a los patrones de comportamiento que ella descubra sobre nosotros. Pero si comunica los patrones aprendidos y hace públicas sus razonamientos, parte del conjunto de seres humanos puede reaccionar de forma no deseada alterando el resultado de la estrategia. ¿Debería ser la Superinteligencia Artificial opaca? Creo que no. No, no deberíamos pedir a una ASI que oculte sus razones “para que funcione”. En un sistema socio-climático, la forma correcta de romper el bucle anti-inductivo no es la opacidad, sino diseñar reglas e incentivos que sigan funcionando aun cuando todos las conozcan. Si la ASI manipula en secreto, las personas pierden capacidad de decidir informadas. Eso erosiona la legitimidad y dispara la desconfianza social. Cuando la gente descubre tácticas opacas, suele rechazar la política (teorías conspiranoicas), justo lo contrario de lo que se buscaba. La clave por lo tanto estará en que conocer la regla/estrategia no la vuelva inútil. Algunos ejemplos de medidas que se podrían tomar son:

** Precio al carbono / peajes de congestión: todo el mundo conoce la regla y, precisamente por eso, cambia conductas de modo predecible (menos emisiones, menos tráfico).

** Códigos de construcción / eficiencia energética: son públicos; aun así, funcionan porque alinean el interés individual con el objetivo social.

** Programas de ayudas con criterios claros: si los criterios son públicos, las personas se adaptan… ¡y eso es lo que queremos! (que adopten aislamiento, renovables, etc.).

## Conclusiones finales

La idea central es diseñar reglas que, aunque todos las “jueguen”, sigan empujando el sistema hacia el atractor deseado por la ASI. El estado final del clima quizás no pueda ser conocido por completo, pero quizás si pueda ser comprendido lo suficiente como para cuidarlo y cuidarnos mejor. Ese conocimiento suficiente es una meta más realista e importante que la omniscencia imposible. 

Cabe mencionar que la ASI ha de ser prudente en cuanto a las acciones a emprender. El clima, al igual que otros sistemas físicos, tiene una flecha del tiempo. Esto quiere decir, que si bien muchas de las ecuaciones deterministas que empleamos para predecir sistemas físicos actúan de igual manera hacia el futuro que hacia el pasado, en la práctica la flecha del tiempo que nos marca la entropía hace que no podamos ir hacia atrás. El clásico ejemplo es cuando revolvemos un café con crema. Al principio la crema está separada del cafe, pero al revolverla se mezcla con el café y se hace una mezcla indisoluble. Esto puede pasar con el clima: hay puntos de no retorno, que una vez cruzados cuesta mucho o resulta imposible volver hacia atrás. Las medidas propuestas por la ASI han de ser reversibles. Esto asimismo es una llamada de atención a la actuación de los seres humanos sobre el clima: hay ciertas acciones que acumuladas pueden tener una vuelta hacia atrás muy costosa o imposible de realizar. 

En este momento estamos lejos de que se puedan llegar a poder implementar estas acciones. Tal y como vimos en la sección sobre el Clima y el Caos, muchas de las predicciones realizadas por los humanos mediante modelos climáticos no han funcionado bien a escala local. Un mecanismo de acción prudente sería, una vez que estuviera desarrollada, probar sus predicciones y probar también los efectos de los mecanismos de acción que nos sugiera. Pero ninguna de estas dos etapas pueden realizar inmediatamente. Para empezar, habría que probar las predicciones de la ASI, y eso llevaría tiempo. Supongamos que tenemos una ASI para el año 2040, y que ese mismo año realiza predicciones sobre el clima a 30 años vista. Tendríamos que esperar 30 años para ver si son correctas. Una vez visto, que son correctas tendríamos que hacer lo mismo con los mecanismos de acción que nos sugiera, y tendríamos que esperar otros 30 años para ver que los resultados son correctos. Por lo tanto, nos plantaríamos en el año 2100 para poder empezar a actuar. Y es que, si queremos ser prudentes, en este tipo de actuaciones no hay atajos si queremos estar seguros de los resultados. 




