project:
  type: website

website:
  title: "mi_blog_caos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/mapa-logistico.qmd
        text: Mapa Logístico
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    math: katex
