project:
  type: website
  output-dir: ../../docs  

website:
  title: "mi_blog_caos"        
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/mapa-logistico.qmd
        text: Mapa Logístico
      - href: posts/cobweb.qmd
        text: Cobweb
      - href: posts/bifurcaciones.qmd
        text: Bifurcaciones
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    math: katex