name: Predicción horaria

# Se ejecuta cada hora
on:
  schedule:
    - cron: '0 * * * *'  # cada hora a minuto 0 (UTC)

jobs:
  run-predice3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          # Instalar librerías necesarias
          pip install pandas numpy torch matplotlib requests

      - name: Run Predice3.py
        run: |
          cd multiestacion/funcionando/c/EstacionVirtual
          python Predice3.py

      - name: Commit and push updated results
        run: |
          cd multiestacion/funcionando/c/EstacionVirtual
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          git commit -m "Update predictions [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd multiestacion/funcionando/c/EstacionVirtual
          python Predice3.py
