name: Daily Weather Data Collection and Commit

on:
  schedule:
    # Run at 1:00 UTC every day (adjust cron expression if needed)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Enables manual triggering

jobs:
  collect-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Set fetch-depth to 0 so you have the full history (needed for committing changes)
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run Your Weather Data Script
      - name: Run Weather Data Script
        run: |
          python meteoblue/DailyScript.py

      - name: Verify PAT is set
        run: echo "PAT token is set."
        env:
          MY_PAT: ${{ secrets.PAT_TOKEN }}

      # Step 5: Commit the updated CSV files to the "data" branch
      - name: Commit CSV files to data branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: data
          message: "Daily update of CSV files - $(date)"
          add: |
            temperatureForecast.csv
            humidityForecast.csv
            pressureForecast.csv
            windForecast.csv
            temperatureRetro.csv
            humidityRetro.csv
            pressureRetro.csv
            windRetro.csv
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
